name: auto-update

on:
  workflow_dispatch:
  schedule:
    - cron:  0 */4 * * *

jobs:
  build:
    name: auto update
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: liamg/github-profile-terminal-action@main
      with:
        theme: dark
        token: ${{ secrets.GITHUB_TOKEN }}
